name: Lint

on:
  push:
    tags-ignore:
      - "**"
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - 'examples/**'
      - 'README.md'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"

      - name: Run ruff (lint)
        run: uvx ruff check .

      - name: Run ruff (format)
        run: uvx ruff format --check .
