name: Tests

on:
  pull_request:
  push:
    tags-ignore:
      - "**"
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - 'examples/**'
      - 'README.md'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install tesseract-ocr --no-install-recommends --no-upgrade --show-progress

      - name: Install requirements
        run: uv sync --all-extras

      - name: Run type checker (mypy)
        run: uv run mypy src

      - name: Run interrogate
        run: uv run interrogate src

      - name: Run unit tests
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          uv run coverage run --rcfile=pyproject.toml -m unittest tests/unit/*.py tests/unit/drivers/*.py
          uv run coverage report
          uv run coveralls

      - name: Run integration tests
        run: |
          uv run python -m unittest tests/integration/*.py
